#!/usr/bin/env python
# -*- encoding=utf8 -*-

'''
FileName:   realtime.py
Author:     Chen Yanfei
@contact:   fasionchan@gmail.com
@version:   $Id$

Description:

Changelog:

'''

import os, sys

from finance.finance import finance

def main():
    homedir = os.path.expanduser('~')
    confdir = os.path.abspath(os.path.join(homedir, '.finance'))
    sys.path.insert(0, confdir)

    from config import stocks_watched, stocks_held
    realtime_table = finance.format_realtime(stocks_watched, stocks_held)

    from config import cash
    forex_realtime_table = finance.format_forex_realtime(cash.keys())
    invest_table = finance.format_market_value(stocks_held, cash)

    print realtime_table
    print forex_realtime_table
    print invest_table

if __name__ == '__main__':
    main()
