#!/usr/bin/env python
# -*- encoding=utf8 -*-

'''
FileName:   realtime.py
Author:     Chen Yanfei
@contact:   fasionchan@gmail.com
@version:   $Id$

Description:

Changelog:

'''

import os, sys

from finance.finance import finance

def main():
    homedir = os.path.expanduser('~')
    confdir = os.path.abspath(os.path.join(homedir, '.finance'))
    sys.path.insert(0, confdir)

    from config import watched_stocks
    finance.show_realtime(*watched_stocks)
    print

    from config import stocks, cash
    finance.show_market_value(stocks, cash)

if __name__ == '__main__':
    main()
